import Footer from "@/components/Footer";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { addCampaign } from "@/services/web3Service";

export default function Create() {
  const [campaign, setCampaign] = useState({
    title: "",
    description: "",
    imageUrl: "",
    videoUrl: ""
  });
  const [message, setMessage] = useState("");

  function onInputChange(evt) {
    setCampaign(prevState => ({ ...prevState, [evt.target.id]: evt.target.value }));
  }

  function btnSaveClick() {
    if (!campaign.title || !campaign.description || !campaign.imageUrl || !campaign.videoUrl) {
      setMessage("Por favor, preencha todos os campos!");
      return;
    }

    setMessage("Salvando... Aguarde...");
    addCampaign(campaign)
      .then(result => {
        setMessage(`✅ Campanha criada com sucesso!\n\nID da Campanha: ${result.campaignId}\n\nCompartilhe esse ID para receber doações!`);
      })
      .catch(err => {
        console.error(err);
        setMessage(err.message || JSON.stringify(err))
      })
  }

  return (
    <>
      <Head>
        <title>CryptAid | Criar nova campanha</title>
        <meta charSet="utf-8" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="container">
        <h1 className="display-5 fw-bold text-body-enphasis lh-1 mb-3">
          Crypt Aid
        </h1>
        <p>Preencha os campos para incluir sua campanha na plataforma.</p>
        <hr className="mb-4" />
        <div className="col-6">
          <div className="form-floating mb-3">
            <input
              type="text"
              id="title"
              className="form-control"
              value={campaign.title}
              onChange={onInputChange}
            />
            <label htmlFor="title">Título: </label>
          </div>
          <div className="form-floating mb-3">
            <textarea
              id="description"
              className="form-control"
              value={campaign.description}
              onChange={onInputChange}
            ></textarea>
            <label htmlFor="description">Descrição: </label>
          </div>
          <div className="form-floating mb-3">
            <input
              type="text"
              id="imageUrl"
              className="form-control"
              value={campaign.imageUrl}
              onChange={onInputChange}
            />
            <label htmlFor="imageUrl">URL da imagem: </label>
          </div>
          <div className="form-floating mb-3">
            <input
              type="text"
              id="videoUrl"
              className="form-control"
              value={campaign.videoUrl}
              onChange={onInputChange}
            />
            <label htmlFor="videoUrl">URL do vídeo: </label>
          </div>
        </div>
        <div className="col-6">
          <input
            type="submit"
            className="btn btn-primary col-12 p-3 mb-2"
            value="Salvar campanha"
            onClick={btnSaveClick}
          />
        </div>
        <div className="col-6">
          <Link href="/" className="btn btn-secondary col-12 p-3">
            Voltar
          </Link>
        </div>
      </div>
      {message ? (
        <div className="alert alert-success p-3 col-6" role="alert">
          {message}
        </div>
      ) : (
        <></>
      )}
      <Footer />
    </>
  );
}